### GET ALL
GET http://localhost:7007/api/accounts
Content-Type: application/json

### CREATE
POST http://localhost:7007/api/accounts
Content-Type: application/json

{
  "username": "12test-username",
  "password": "test-password",
  "role": {
    "name": "REGULAR"
  }
}

### READ BY ID
GET http://localhost:7007/api/accounts/1
Content-Type: application/json

### UPDATE
PUT http://localhost:7007/api/accounts/1
Content-Type: application/json

{
  "username": "updated-username",
  "password": "updated-password",
  "role": {
    "name": "NONE"
  }
}

### DELETE
DELETE http://localhost:7007/api/accounts/1
Content-Type: application/json
