### Logining with admin credentials
POST http://localhost:7007/api/security/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}



### Create game manually
POST http://localhost:7007/api/games
Content-Type: application/json

{
  "name": "mudnsadfh,fni",
  "account": {
    "id": 1
  }
}


###
POST http://localhost:7007/api/licences
Content-Type: application/json

{
  "username": "user21",
  "password": "123456",
  "email": "user1@llkjljl.com",
  "pcNumber": 2,
  "gameId": 18,
  "status": "ACTIVE"
}



### Get all licenses
GET http://localhost:7007/api/licences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImV4cCI6MTc0NTQ0MzI2MCwiaWF0IjoxNzQ1NDM2MDYwLCJ1c2VybmFtZSI6ImFkbWluIn0.RW7lGCNSE170II2nV26epdUhcJQYCce5RmfhylaZ67I
Accept: application/json


### editing license 

PUT http://localhost:7007/api/licences/36
Content-Type: application/json

{
  "id": 36,
  "username": "user21",
  "password": "newpass456",
  "email": "user1@llkjljl.com",
  "pcNumber": 4,
  "gameId": 18,
  "status": "INACTIVE"
}

### Get all games
GET http://localhost:7007/api/accounts


### get account by id 

GET http://localhost:7007/api/accounts/1

