@startuml "Java Backend Structure"

' ======================== APPLICATION PACKAGE ========================
' Latest updated: 30.04.2025
package "application" {
    class Application {
        + {static} void main (String[] args)
    }
    
    package "config" {
        class ApplicationConfig {
            - Javalin app
            - {static} ApplicationConfig instance
            - ApplicationConfig()
            + {static} ApplicationConfig getInstance()
            + ApplicationConfig initiateServer()
            + ApplicationConfig startServer(int port)
            + ApplicationConfig setRoute(EndpointGroup route)
        }
    }
}

' ======================== CONTROLLER PACKAGE ========================
' Latest updated: 30.04.2025
package "controller" {
        interface IController {
        + getAll(): Handler
        + getById(): Handler
        + create(): Handler
        + update(): Handler
        + delete(): Handler
    }

    class SecurityController {
        - {static} final String SECRET_KEY
        - {static} final String timestamp
        - final AccountDAO accountDAO
        + SecurityController(EntityManagerFactory emf)
        + Handler login()
        - String createToken(String username, Role role) throws TokenCreationException
        + boolean tokenIsValid(String token)
        + boolean hasRole(String token, String requiredRole)
        + Handler requireRole(String role, Handler handler)
        + JWTClaimsSet decodeToken(String token)
    }
    
    class AccountController implements IController {
        - {static} final String timestamp
        - final AccountDAO dao
        + AccountController(EntityManagerFactory emf)
        + AccountDTO converter(Account account)
        + Handler getAll()
        + Handler getById()
        + Handler create()
        + Handler update()
        + Handler delete()
    }

    class GameController implements IController {
        - {static} final String timestamp
        - final GameDAO dao
        + GameController(EntityManagerFactory emf)
        + GameDTO converter(Game game)
        + Handler getAll()
        + Handler getById()
        + Handler create()
        + Handler update()
        + Handler delete()
    }
    
    class InformationController implements IController {
        - {static} final String timestamp
        - final InformationDAO dao
        + InformationController(EntityManagerFactory emf)
        + InformationDTO converter(Information information)
        + Handler getAll()
        + Handler getById()
        + Handler create()
        + Handler update()
        + Handler delete()
    }
    
    class LicenseController implements IController {
        - {static} final String timestamp
        - final LicenseDAO dao
        + LicenseController(EntityManagerFactory emf)
        + LicenseDTO converter(License license)
        + Handler getAll()
        + Handler getById()
        + Handler create()
        + Handler update()
        + Handler delete()
    }
    
    class QAController implements IController {
        - {static} final String timestamp
        - final QADAO dao
        + QAController(EntityManagerFactory emf)
        + QADTO converter(QA qa)
        + Handler getAll()
        + Handler getById()
        + Handler create()
        + Handler update()
        + Handler delete()
    }
    
    class RoleController implements IController {
        - {static} final String timestamp
        - final RoleDAO dao
        + RoleController(EntityManagerFactory emf)
        + RoleDTO converter(Role role)
        + Handler getAll()
        + Handler getById()
        + Handler create()
        + Handler update()
        + Handler delete()
    }
    
    class TodoController implements IController {
        - {static} final String timestamp
        - final TodoDAO dao
        + TodoController(EntityManagerFactory emf)
        + TodoDTO converter(Todo todo)
        + Handler getAll()
        + Handler getById()
        + Handler create()
        + Handler update()
        + Handler delete()
    }
}

' ======================== DAO PACKAGE ========================
' Latest updated: 30.04.2025
package "dao" {
    interface IDAO<T> {
        + List<T> getAll()
        + T getById(int id)
        + T create(T entity)
        + T update(T entity)
        + T delete(int id)
    }

    abstract class DAO<T> implements IDAO<T> {
        # {static} EntityManagerFactory emf
        # {static} String timestamp
        - final Class<T> entityClass
        # DAO (Class<T> entityClass)
        + Role getRoleByName(Role.RoleName name)
        + Account getAccountByUsername(String username)
        + Game getGameByName(String name)
        - Account attachAccountWithRole(EntityMange em, Account sourceAccount)
        - private <E> void removeFromCollection(Collection<E> collection, E entity)
        + List<T> getAll()
        + T getById(int id)
        + T create(T entity)
        + T update(T entity)
        + T delete(int id)
    }

    class AccountDAO extends DAO<Account> {
        - {static} AccountDAO instance
        - {static} EntityManagerFactory emf
        - AccountDAO()
        + {static} AccountDAO getInstance(EntityManagerFactory emf)
        + Account verifyLogin(String username, String password)
        + List<Account> getAll()
    }

    class GameDAO extends DAO<Game> {
        - {static} GameDAO instance
        - GameDAO()
        + {static} GameDAO getInstance(EntityManagerFactory emf)
        + Account getAccountById(int id)
    }
    
    class InformationDAO extends DAO<Information> {
        - {static} InformationDAO instance
        - InformationDAO()
        + {static} InformationDAO getInstance(EntityManagerFactory emf)
        + Account getAccountById(int id)
    }
    
    class LicenseDAO extends DAO<License> {
        - {static} LicenseDAO instance
        - LicenseDAO()
        + {static} LicenseDAO getInstance(EntityManagerFactory emf)
        + Game getGameById(int id)
    }
    
    class QADAO extends DAO<QA> {
        - {static} QADAO instance
        - QADAO()
        + {static} QADAO getInstance(EntityManagerFactory emf)
        + Account getAccountById(int id)
    }
    
    class RoleDAO extends DAO<Role> {
        - {static} RoleDAO instance
        - RoleDAO()
        + {static} RoleDAO getInstance(EntityManagerFactory emf)
    }
    
    class TodoDAO extends DAO<Todo> {
        - {static} TodoDAO instance
        - TodoDAO()
        + {static} TodoDAO getInstance(EntityManagerFactory emf)
        + Account getAccountById(int id)
    }
}
' ======================== DATA PACKAGE ========================
' Latest updated: 01.05.2025
package "data" {
    class PopulateData {
        + {static} void populateData(EntityManagerFactory emf)
    }
}
' ======================== DTO PACKAGE ========================
' Latest updated: 01.05.2025
package "dto" {
    class AccountDTO {
        - int id
        - String username
        - String password
        - Role role
        - List<Todo> todos
        - List<Information> information
        - List<Game> games
        - List<QA> qas
        + AccountDTO(String username, String password)
        + AccountDTO(Account account)
        + Set<String> getRoles()
        + String toString()
    }
    
    class GameDTO {
        - int id
        - String name
        - List<License> licenses
        - int accountID
    }
    
    class InformationDTO {
        - int id
        - String description
        - int accountId
        - String importanceLevel
    }
    
    class LicenseDTO {
        - int id
        - String username
        - String password
        - String email
        - int pcNumber
        - Game game
        - License.LicenseStatus status
    }
    
    class QADTO {
        - int id
        - String question
        - String answer
        - int accountId
    }
    
    class RoleDTO {
        - int id
        - String name
        - List<Header> headers
        - List<Footer> footers
    }
    
    class TodoDTO {
        - int id
        - LocalDate date
        - String description
        - Todo.Status status
        - Todo.Source source
        - String done_by
        - Account account
    }
    
    class TokenDTO {
        - String token
        - String username
        - String role
        - int id
        + String toString()
    }
}

' ======================== EXCEPTION PACKAGE ========================
' Latest updated: 01.05.2025
package "exception" {
    class ApiException extends Exception {
        - final int statusCode
        - final String timeStamp
        + ApiException(int statusCode, String message, String timestamp)
    }
}

' ======================== PERSISTENCE PACKAGE ========================
' Latest updated: 01.05.2025
package "persistence" {
    package "config" {
        class HibernateConfig {
            - {static} EntityManagerFactory entityManagerFactory
            - {static} EntityManagerFactory buildEntityFactoryConfig()
            - {static} EntityManagerFactory setupHibernateConfigurationForTesting()
            - {static} EntityManagerFactory getEntityManagerFactory(Configuration, Properties)
            - {static} void getAnnotationConfiguration(Configuration)
            - {static} EntityManagerFactory getEntityManagerFactoryConfigDevelopment()
            - {static} void getEntityManagerFactoryConfigTest()
            + {static} EntityManagerFactory getEntityManagerFactoryConfig(boolean isTest)
        }
    }
    
    package "model" {
        class Account {
            - String salt
            - int id
            - String username
            - String password
            - Role role
            - List<Todo> todos
            - List<Information> informations
            - List<Game> games
            - List<QA> qas
            + void setPassword(String password)
            + Account(String username, String password, Role role)
            + Account(String username, String password)
            + boolean verifyPassword(String password)
        }
        
        class Role {
            - int id
            - RoleName name
            + Role(RoleName name)
            + enum RoleName { REGULAR, NONE }
        }
        
        class Information {
            - int id
            - String description
            - ImportanceLevel importanceLevel
            - Account account
            + Information(String description, Account account, ImportanceLevel importanceLevel)
            + enum ImportanceLevel {LOW, MEDIUM, HIGH}
        }
        
        class QA {
            - int id
            - String question
            - String answer
            - Account account
            + QA(String question, String answer, Account account)
        }
        
        class Todo {
            - int id
            - LocalDate date
            - String description
            - Status status
            - Source source
            - String done_by
            - Account account
            + Todo(LocalDate date, String description, Status status, Source source, String done_by, Account account)
            + Todo(LocalDate date, String description, Status status, Source source, Account account)
            # void onUpdate()
            - String getCurrentUser()
            # void onCreate()
            + enum Source {GAMEHUB, STORE}
            + enum Status {PENDING, IN_PROGRESS, COMPLETED}
        }
        
        class Game {
            - int id
            - String name
            - Account account
            - List<License> licenses
            + Game(String name, Account account)
            + Game(int id, String name, Account account)
            + Game(int id)
        }
        
        class License {
            - int id
            - String username
            - String password
            - String email
            - int pcNumber
            - LicenseStatus status
            - Game game
            + License(String username, String password, String email, License.LicenseStatus status, Game game)
            + enum LicenseStatus { ACTIVE, INACTIVE }
        }
    }
}

' ======================== ROUTE PACKAGE ========================
' Latest updated: 01.05.2025
package "route" {
    class Route {
        ~ SecurityRoute securityRoute
        ~ AccountRoute accountRoute
        ~ GameRoute gameRoute
        ~ InformationRoute informationRoute
        ~ LicenseRoute licenseRoute
        ~ QARoute qaRoute
        ~ RoleRoute roleRoute
        ~ TodoRoute todoRoute
        + Route(EntityManagerFactory emf)
        + EndpointGroup addRoutes()
    }
    
    class SecurityRoute {
        - final SecurityController securityController
        + SecurityRoute(EntityManagerFactory emf)
        + EndpointGroup authRoutes()
    }
    
    class AccountRoute {
        - final AccountController accountController
        + AccountRoute(EntityManagerFactory emf)
        + EndpointGroup itemRoutes()
    }
    
    class GameRoute {
        - final GameController gameController
        + GameRoute(EntityManagerFactory emf)
        + EndpointGroup itemRoutes()
    }

    class InformationRoute {
        - final InformationController informationController
        + InformationRoute(EntityManagerFactory emf)
        + EndpointGroup itemRoutes()
    }
    
    class LicenseRoute {
        - final LicenseController licenseController
        + LicenseRoute(EntityManagerFactory emf)
        + EndpointGroup itemRoutes()
    }
    
    class QARoute {
        - final QAController qaController
        + QARoute(EntityManagerFactory emf)
        + EndpointGroup itemRoutes()
    }
    
    class RoleRoute {
        - final RoleController roleController
        + RoleRoute(EntityManagerFactory emf)
        + EndpointGroup itemRoutes()
    }
    
    class TodoRoute {
        - final TodoController todoController
        + TodoRoute(EntityManagerFactory emf)
        + EndpointGroup itemRoutes()
    }
}

' ======================== UTILITY PACKAGE ========================
' Latest updated: 01.05.2025
package "utility" {
    class DateUtil {
        + {static} final SimpleDateFormat dateFormat
        + {static} String timeStamp
    }
}

' ======================== RELATIONSHIPS ========================
' Application relationships
' Latest updated: 01.05.2025
Application <-- ApplicationConfig
Application <-- HibernateConfig
Application <-- Route
Application <-- PopulateData


' Route relationships
' Latest updated: 01.05.2025
Route <-- SecurityRoute
Route <-- AccountRoute
Route <-- GameRoute
Route <-- InformationRoute
Route <-- LicenseRoute
Route <-- QARoute
Route <-- RoleRoute
Route <-- TodoRoute


' Route to Controller relationships
' Latest updated: 01.05.2025
SecurityRoute <-- SecurityController
AccountRoute <-- AccountController
GameRoute <-- GameController
InformationRoute <-- InformationController
LicenseRoute <-- LicenseController
QARoute <-- QAController
RoleRoute <-- RoleController
TodoRoute <-- TodoController

' Controller to DAO relationships
' Latest updated: 01.05.2025
SecurityController --> AccountDAO
AccountController --> AccountDAO
GameController --> GameDAO
InformationController --> InformationDAO
LicenseController --> LicenseDAO
QAController --> QADAO
RoleController --> RoleDAO
TodoController --> TodoDAO

' Controller to DTO relationships
' Latest updated: 01.05.2025
AccountController <-- AccountDTO
GameController <-- GameDTO
InformationController <-- InformationDTO
LicenseController <-- LicenseDTO
QAController <-- QADTO
RoleController <-- RoleDTO
TodoController <-- TodoDTO
SecurityController <-- TokenDTO

' Controller to Exception relationships
' Latest updated: 01.05.2025
SecurityController --> ApiException
AccountController --> ApiException
GameController --> ApiException
InformationController --> ApiException
LicenseController --> ApiException
QAController --> ApiException
RoleController --> ApiException
TodoController --> ApiException

' Model relationships
' Latest updated: 01.05.2025
Account <-- Role
Account <-- Todo
Account <-- Information
Account <-- Game
Account <-- QA
Game <-- License
Game <-- Account

' DAO to Model relationships
' Latest updated: 01.05.2025
AccountDAO <-- Account
GameDAO <-- Game
InformationDAO <-- Information
LicenseDAO <-- License
QADAO <-- QA
RoleDAO <-- Role
TodoDAO <-- Todo

' Utility relationships
' Latest updated: 01.05.2025
SecurityController <-- DateUtil
AccountController <-- DateUtil
GameController <-- DateUtil
InformationController <-- DateUtil
LicenseController <-- DateUtil
QAController <-- DateUtil
RoleController <-- DateUtil
TodoController <-- DateUtil

@enduml