@startuml
'https://plantuml.com/class-diagram

'Entities
class Person {
Name
Role
}

class Todo {
Date
Location
Task
}

class Game {
Name
}

class License {
Email
Password
}

'Relations
Person "0..*" -- "1" Todo
Person "0..*" -- "1" Game
Game "0..*" -- "1" License

hide methods
@enduml